spring.config.import=optional:file:.env[.properties]

spring.application.name=backend-app-dat-xe

spring.datasource.url=${DB_POSTGRESQL_URI}
spring.datasource.username=${DB_POSTGRESQL_USERNAME}
spring.datasource.password=${DB_POSTGRESQL_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.redis.url=${DB_REDIS_URI}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

mapbox.api.navigation.url=https://api.mapbox.com
mapbox.api.navigation.key=${MAPBOX_PUBLIC_TOKEN}